- name: Instalando o docker
  shell: curl -fsSL https://get.docker.com | bash

- name: Add as chaves do repo apt do k8s
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg 
    state: present

- name: Add repo do k8s  
  add_repository: 
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    
- name: Instalando os pacotes kubeadm, kublet e kubctl
  apt:
    name: "{{ packeages }}"
  vars: 
    packages:
    - kubelet
    - kubeadm
    - kubectl
