---
# vars file for install-monit-tools
url_repo_helm: https://kubernetes-charts.storage.googleapis.com
deploy_prometheus: "--set prometheusOperator.createCustomResource=false prometheus-prometido stable/prometheus-operator"