---
- name: download helm
  get_url:
     url: "{{ helm_url }}"
     dest: /tmp/get_helm.sh
     mode: 0755
  ignore_errors: true
  register: download

- name: instalando o helm
  shell:
    /tmp/get_helm.sh
  when:
    - download.failed | bool == false
  register: install_helm

- name:
  debug: var=install_helm
